<?php //NewCars_out 
  return array (
  'folder' => 'edit',
  'bigparent' => '593',
  'fields' => 
  array (
    0 => 'pagetitle',
    1 => 'published',
    2 => 'configuration_id',
    3 => 'doors-count',
    4 => 'generation',
    5 => 'generation_name',
    6 => 'is_restyle',
    7 => 'mark_id',
    8 => 'model_class',
    9 => 'model_id',
    10 => 'rus_model',
    11 => 'year',
    12 => 'equipment',
    13 => 'gear',
    14 => 'mark',
    15 => 'model',
    16 => 'modification',
    17 => 'engine_power',
    18 => 'engine_volume',
    19 => 'drive',
    20 => 'wheel',
    21 => 'сountry',
    22 => 'body_type',
    23 => 'fuel',
    24 => 'price',
    25 => 'car-price',
  ),
  'tree' => '3',
  'tvpic' => '',
  'order' => 'id',
  'orderas' => 'desc',
  'filters' => '',
  'addwhere' => 'c.template=28',
  'save_config' => 'NewCars_out',
) ?>