<?php //car-OLD-out 
  return array (
  'folder' => 'export',
  'stparent' => '27',
  'fieldz' => 
  array (
    0 => 'pagetitle',
    1 => 'description',
    2 => 'published',
    3 => 'doors-count',
    4 => 'vin',
    5 => 'owners',
    6 => 'year',
    7 => 'equipment',
    8 => 'gear',
    9 => 'mark',
    10 => 'metallic',
    11 => 'model',
    12 => 'modification',
    13 => 'engine_power',
    14 => 'engine_volume',
    15 => 'drive',
    16 => 'run',
    17 => 'pts',
    18 => 'wheel',
    19 => 'condition',
    20 => 'body_type',
    21 => 'fuel',
    22 => 'car_photos',
    23 => 'car-price',
  ),
  'depth' => '1',
  'dm' => ';',
  'filters' => '',
  'addwhere' => '',
  'load_config' => 'car-old-out.php',
  'save_config' => 'car-OLD-out',
) ?>